### ISSUE TITLE
安装有问题

### ISSUE THREAD

**Issue by weimingxuan** [sunniejs/vue_canvas_poster#2]
cnpm、npm安装成功
问题1.运行的时候提示：“To install it, you can run: npm install --save vue-canvas-poster”
全局引用和页面引用都不行

同样的我找到了一个和这个类似的插件“vue-canvas-poster-yufan”，完美运行使用，但是不支持二维码。请帮忙解决一下，急

**Comment by weimingxuan** [comment]
把“package.json“中的main设置成“src/lib/index.js”

**Comment by Arc-zlz** [comment]
> 把“package.json“中的main设置成“src/lib/index.js”
"main": "src/lib/index.js",  还是没用,请问时设置的不对吗

**Comment by xiabuyuanyu** [comment]
你好，我图片一直显示
![image](https://user-images.githubusercontent.com/25945540/66283610-b8b55080-e8f6-11e9-8e76-7efea880f6cd.png)
![image](https://user-images.githubusercontent.com/25945540/66283675-f31eed80-e8f6-11e9-8f9e-489b6316159d.png)
![image](https://user-images.githubusercontent.com/25945540/66283681-ffa34600-e8f6-11e9-8017-ca0c36fdbb4a.png)
从后台得到的，或者网上找的图片也不行，可是换成你例子里的就可以，需要怎么处理？
![image](https://user-images.githubusercontent.com/25945540/66283659-e4d0d180-e8f6-11e9-9353-84d074929af7.png)

**Comment by wangpanlin** [comment]
> 你好，我图片一直显示
> ![image](https://user-images.githubusercontent.com/25945540/66283610-b8b55080-e8f6-11e9-8e76-7efea880f6cd.png)
> ![image](https://user-images.githubusercontent.com/25945540/66283675-f31eed80-e8f6-11e9-8f9e-489b6316159d.png)
> ![image](https://user-images.githubusercontent.com/25945540/66283681-ffa34600-e8f6-11e9-8017-ca0c36fdbb4a.png)
> 从后台得到的，或者网上找的图片也不行，可是换成你例子里的就可以，需要怎么处理？
> ![image](https://user-images.githubusercontent.com/25945540/66283659-e4d0d180-e8f6-11e9-9353-84d074929af7.png)

这个我也遇到了，可能是因为图片大小的问题，估计超过100K的就不成功

**Comment by sunniejs** [comment]
使用者可以通过按照最新版本，目前已经没有上述的几个问题了
