### ISSUE TITLE
安装成功 但npm run dev提示依赖未找到

### ISSUE THREAD

**Issue by lxow456** [sunniejs/vue_canvas_poster#9]
npm install成功之后，但npm run dev一直提示：   
&emsp;This dependency was not found: * vue-canvas-poster in ./src/main.js   
解决办法：将vue-canvas-poster的package.json中的main字段改为'./src/lib/index.js'

**Comment by Ken-LK** [comment]
谢谢，我也遇到同样的问题

**Comment by sunniejs** [comment]
对不起，我犯了一个低级的错误，请升级到最新的1.0.2版本或最新版本。
作为一个开源者，我需要抱着严谨的态度，做每一次升级。
对使用者负责人，再次抱歉！
